src/Entity/Locality.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LocalityRepository")
 * @ORM\Table(name="localities")
 */
class Locality
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $locality;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Location", mappedBy="locality")
     */
    private $locations;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getLocality(): ?string
    {
        return $this->locality;
    }

    public function setLocality(string $locality): self
    {
        $this->locality = $locality;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setLocality($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getLocality() === $this) {
                $location->setLocality(null);
            }
        }

        return $this;
    }
}

src/Form/LocalityType.php
<?php

namespace App\Form;

use App\Entity\Locality;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocalityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('slug')
            ->add('designation')
            ->add('address')
            ->add('location_id')
            ->add('website')
            ->add('phone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Locality::class,
        ]);
    }
}

src/Controller/LocalityController.php
<?php

namespace App\Controller;

use App\Entity\Locality;
use App\Form\Locality1Type;
use App\Repository\LocalityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/locality")
 */
class LocalityController extends AbstractController
{
    /**
     * @Route("/", name="locality_index", methods={"GET"})
     */
    public function index(LocalityRepository $localityRepository): Response
    {
        return $this->render('locality/index.html.twig', [
            'localities' => $localityRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="locality_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $locality = new Locality();
        $form = $this->createForm(Locality1Type::class, $locality);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($locality);
            $entityManager->flush();

            return $this->redirectToRoute('locality_index');
        }

        return $this->render('locality/new.html.twig', [
            'locality' => $locality,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="locality_show", methods={"GET"})
     */
    public function show(Locality $locality): Response
    {
        return $this->render('locality/show.html.twig', [
            'locality' => $locality,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="locality_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Locality $locality): Response
    {
        $form = $this->createForm(Locality1Type::class, $locality);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('locality_index');
        }

        return $this->render('locality/edit.html.twig', [
            'locality' => $locality,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="locality_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Locality $locality): Response
    {
        if ($this->isCsrfTokenValid('delete'.$locality->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($locality);
            $entityManager->flush();
        }

        return $this->redirectToRoute('locality_index');
    }
}

templates/locality/_delete_form.html.twig
<form method="post" action="{{ path('locality_delete', {'id': locality.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ locality.id) }}">
    <button class="btn">Delete</button>
</form>

templates/locality/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Locality{% endblock %}

{% block body %}
    <h1>Edit Locality</h1>

    {{ include('locality/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('locality_index') }}">back to list</a>

    {{ include('locality/_delete_form.html.twig') }}
{% endblock %}

templates/locality/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Locality index{% endblock %}

{% block body %}
    <h1>Locality index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Postal_code</th>
                <th>Locality</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for locality in localities %}
            <tr>
                <td>{{ locality.id }}</td>
                <td>{{ locality.postalCode }}</td>
                <td>{{ locality.locality }}</td>
                <td>
                    <a href="{{ path('locality_show', {'id': locality.id}) }}">show</a>
                    <a href="{{ path('locality_edit', {'id': locality.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('locality_new') }}">Create new</a>
{% endblock %}

templates/locality/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Locality{% endblock %}

{% block body %}
    <h1>Create new Locality</h1>

    {{ include('locality/_form.html.twig') }}

    <a href="{{ path('locality_index') }}">back to list</a>
{% endblock %}

templates/locality/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'une localité{% endblock %}

{% block body %}
    <h1>{{ locality.postalCode }} {{ locality.locality }}</h1>
    
    <ul>
    {% for location in locality.locations %}
        <li>{{ location.designation }}</li>
    {% endfor %}
    </ul>

{% endblock %}