src/Entity/Representation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
/**
 * @ORM\Entity(repositoryClass="App\Repository\RepresentationRepository")
 * @ORM\Table(name="representations")
 */
class Representation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Show", inversedBy="representations")
     * @ORM\JoinColumn(nullable=false, name="show_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $the_show;

    /**
     * @ORM\Column(type="datetime")
     */
    private $schedule;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="representations")
     * @ORM\JoinColumn(nullable=false, name="location_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $the_location;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheShow(): ?Show
    {
        return $this->the_show;
    }

    public function setTheShow(?Show $the_show): self
    {
        $this->the_show = $the_show;

        return $this;
    }

    public function getSchedule(): ?\DateTimeInterface
    {
        return $this->schedule;
    }

    public function setSchedule(\DateTimeInterface $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getTheLocation(): ?Location
    {
        return $this->the_location;
    }

    public function setTheLocation(?Location $the_location): self
    {
        $this->the_location = $the_location;

        return $this;
    }
}

src/Form/RepresentationType.php
<?php

namespace App\Form;

use App\Entity\Representation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RepresentationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('schedule')
            ->add('the_show')
            ->add('the_location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Representation::class,
        ]);
    }
}

src/Controller/RepresentationController.php
<?php

namespace App\Controller;

use App\Entity\Representation;
use App\Form\RepresentationType;
use App\Repository\RepresentationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/representation")
 */
class RepresentationController extends AbstractController
{
    /**
     * @Route("/", name="representation_index", methods={"GET"})
     */
    public function index(RepresentationRepository $representationRepository): Response
    {
        return $this->render('representation/index.html.twig', [
            'representations' => $representationRepository->findAll(),
            'resource'=>'representation',
        ]);
    }

    /**
     * @Route("/new", name="representation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $representation = new Representation();
        $form = $this->createForm(RepresentationType::class, $representation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($representation);
            $entityManager->flush();

            return $this->redirectToRoute('representation_index');
        }

        return $this->render('representation/new.html.twig', [
            'representation' => $representation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="representation_show", methods={"GET"})
     */
    public function show(Representation $representation): Response
    {
        return $this->render('representation/show.html.twig', [
            'representation' => $representation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="representation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Representation $representation): Response
    {
        $form = $this->createForm(RepresentationType::class, $representation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('representation_index');
        }

        return $this->render('representation/edit.html.twig', [
            'representation' => $representation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="representation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Representation $representation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$representation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($representation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('representation_index');
    }
}

templates/representation/_delete_form.html.twig
<form method="post" action="{{ path('representation_delete', {'id': representation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ representation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/representation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/representation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Representation{% endblock %}

{% block body %}
    <h1>Edit Representation</h1>

    {{ include('representation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('representation_index') }}">back to list</a>

    {{ include('representation/_delete_form.html.twig') }}
{% endblock %}

templates/representation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des représentations{% endblock %}

{% block body %}
    <h1>Liste des {{ resource }}</h1>

    <ul>
    {% for representation in representations %}
        <li>{{ representation.theShow.title }}
            {% if representation.theLocation %}
            - <span>{{ representation.theLocation.designation }}</span>
            {% endif %}
            - <datetime>{{ representation.schedule|date('d-m-Y H:i') }}</datetime>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/representation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Representation{% endblock %}

{% block body %}
    <h1>Create new Representation</h1>

    {{ include('representation/_form.html.twig') }}

    <a href="{{ path('representation_index') }}">back to list</a>
{% endblock %}

templates/representation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'une représentation{% endblock %}

{% block body %}
    <article>
        <h1>Représentation du {{ representation.schedule|date('d/m/Y') }} à {{ representation.schedule|date('G:i') }}</h1>
        <p><strong>Spectacle:</strong> {{ representation.theShow.title }}</p>

        <p><strong>Lieu:</strong> 
        {% if representation.theLocation %}
        {{ representation.theLocation.designation }}
        {% elseif representation.theShow.location %}
        {{ representation.theShow.theLocation.designation }}
        {% else %}
        <em>à déterminer</em>
        {% endif %}
        </p>
{% endblock %}